feat: geo-blocking
WalletConnect/verify-server pull request #51
Opened 2023-09-30 05:59 UTC by xav

# Description

Integrates the geoblocking feature from utils-rs. Currently blocked countries: KP, IR, CU, SY.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-09-30 08:21 UTC, xDarksome requested changes
Aws brings a lot of dependencies judging by the `Cargo.lock` :smile: 
Also, there's a bunch of new `-rustls` deps, which is strange, because this service should already use them. I'll check the TLS config later

2023-09-30 08:21 UTC, xDarksome commented on src/http_server/mod.rs
> +    geoip_resolver: Option<Arc<MaxMindResolver>>,
No need to directly depend on impl details here
```suggestion
    geoip_resolver: Option<impl geoip::Resolver>,
```

2023-09-30 08:21 UTC, xDarksome commented on src/http_server/mod.rs
> +        block::{middleware::GeoBlockLayer, BlockingPolicy},
`BlockingPolicy` name doesn't have a context to it, we should probably modify `geoip` in a way so it's possible to use it as `geoip::BlockingPolicy` or `geiop::block::Policy`

```suggestion
        block::{middleware::GeoBlockLayer, GeoBlockingPolicy},
```

2023-09-30 08:21 UTC, xDarksome commented on src/http_server/mod.rs
> +        Router::new().layer(GeoBlockLayer::new(
[Layers](https://docs.rs/axum/latest/axum/struct.Router.html#method.layer) and routes are being applied in a reversed order, so this one should be the last.

Also, I think this function adds more boilerplate. Let's just do it in the `run` fn:
````rust
    let router = Router::new()
    // ....
    .layer(metrics_layer);

    let router = if let Some(resolver) = geoip_resolver { .. } else { router };
````

2023-09-30 08:21 UTC, xDarksome commented on src/main.rs
> +async fn get_s3_client(config: &Configuration) -> S3Client {
Can we have this s3 logic somewhere in `utils-rs` as well?

2023-10-01 06:56 UTC, heilhead commented on src/http_server/mod.rs
> +        Router::new().layer(GeoBlockLayer::new(
It's probably not gonna work like that unless you box it, since the returned types would be different.

2023-10-01 06:58 UTC, heilhead commented on src/main.rs
> +async fn get_s3_client(config: &Configuration) -> S3Client {
I was thinking about the same, but the s3 logic is pretty small (a few lines of code). Most of that boilerplate is AWS config and client initialization. Let's think about a good abstraction, specifically for use in ECS, so that it's a one-liner to integrate. But that's out of scope of this PR.

2023-10-01 07:07 UTC, heilhead approved these changes
Looks good, but hard to say from code if it works or not. Did you test it?

2023-10-01 07:07 UTC, heilhead commented on src/main.rs
> +    let aws_config = match &config.s3_endpoint {
Minor: I'd use an `if let Some(..) = .. { .. } else { .. }` statement here instead.

2023-10-01 07:07 UTC, heilhead commented on src/main.rs
> +    match (&config.geoip_db_bucket, &config.geoip_db_key) {
Same here, `if let` is preferable in my opinion.

2023-10-01 07:07 UTC, heilhead commented on terraform/ecs/variables.tf
> +variable "geoip_db_bucket_name" {
How are these created - manually outside of terraform?

2023-10-02 06:56 UTC, xav commented on terraform/ecs/variables.tf
> +variable "geoip_db_bucket_name" {
Yeah, it's done outside this project, and it's not the relay's one, it's just where we store the geo-db. It's not related to any specific project really.

2023-10-02 06:58 UTC, xav commented on src/main.rs
> +    let aws_config = match &config.s3_endpoint {
I actually prefer the `match` one, easier to scan IMO.
Performance-wise, it should be the same.

2023-10-02 07:03 UTC, xDarksome commented on src/main.rs
> +    let aws_config = match &config.s3_endpoint {
I would even use `.map().unwrap_or()` here. 
But `match` is alright, and I agree that it's more readable than `if else`

2023-10-02 07:24 UTC, xav commented on src/http_server/mod.rs
> +        Router::new().layer(GeoBlockLayer::new(
Thanks for the info

2023-10-02 07:27 UTC, xav commented on src/http_server/mod.rs
> +    geoip_resolver: Option<Arc<MaxMindResolver>>,
That I can believe, the AWS code is not particularly pretty.

2023-10-02 07:28 UTC, xav commented on src/main.rs
> +    let aws_config = match &config.s3_endpoint {
I'm not sure you won't get ownership issues with `.map().unwrap_or()`

2023-10-02 07:31 UTC, xav commented on src/main.rs
> +    let aws_config = match &config.s3_endpoint {
And again, I don't think there should be a huge difference in the compiled version. `match` might look inelegant and naive, but it's reader-friendly.

2023-10-02 07:36 UTC, xDarksome approved these changes
LGTM

Please, fix the clippy warning

2023-10-02 07:37 UTC, xDarksome commented on src/http_server/mod.rs
> +    geoip_resolver: Option<Arc<MaxMindResolver>>,
What about this suggestion?

2023-10-02 07:56 UTC, xav commented on src/http_server/mod.rs
> +    geoip_resolver: Option<Arc<MaxMindResolver>>,
'Send' and 'Sync' are not on the trait, which is an issue here. Something we can fix in `utils` later on but right now that makes no difference since we only have one resolver.

2023-10-02 07:57 UTC, xav commented
> Looks good, but hard to say from code if it works or not. Did you test it?

The parts have been tested individually, but there are not integration tests in the project

2023-10-02 07:58 UTC, xDarksome commented on src/http_server/mod.rs
> +    geoip_resolver: Option<Arc<MaxMindResolver>>,
```rust
geoip_resolver: Option<impl geoip::Resolver + Send + Sync>,
````
But you're right, it should probably be on the trait itself

2023-10-02 14:12 UTC, merged