chore: upgrade deps
WalletConnect/verify-server pull request #77
Opened 2024-04-08 20:45 UTC by chris13524

# Description

Resolves # (issue)

## How Has This Been Tested?

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2024-04-11 11:04 UTC, geekbrother approved these changes

2024-04-11 18:40 UTC, xDarksome commented on rustfmt.toml
> +## We only use settings available in the stable channel
Why?

2024-04-11 18:46 UTC, xDarksome requested changes

2024-04-11 18:46 UTC, xDarksome commented on src/event_sink/s3.rs
> +                export_prefix: format!("notify/{}", data_kind.as_str()),
![image](https://github.com/WalletConnect/verify-server/assets/22872975/aa3e5ac3-0e69-4cf0-a70b-16238777fff0)

2024-04-11 21:04 UTC, chris13524 commented on rustfmt.toml
> +## We only use settings available in the stable channel
I just copied what Xav did for many of the other repos. The shared CI runs the formatter with stable `cargo` not nightly, so we can't use nightly fmt options.

2024-04-11 21:05 UTC, chris13524 commented on src/event_sink/s3.rs
> +                export_prefix: format!("notify/{}", data_kind.as_str()),
```suggestion
                export_prefix: format!("verify-server/{}", data_kind.as_str()),
```

2024-04-11 21:05 UTC, chris13524 commented on src/event_sink/s3.rs
> +                export_prefix: format!("notify/{}", data_kind.as_str()),
Good catch on the name, fixed in https://github.com/WalletConnect/verify-server/pull/77/commits/02ca2b516f39585cd9500535cb657d1594aa58d0

2024-04-12 08:12 UTC, xDarksome commented on rustfmt.toml
> +## We only use settings available in the stable channel
Can we just set `nightly` for `fmt` on CI? The stable `fmt` is very limited

2024-04-12 11:54 UTC, chris13524 commented on src/event_sink/s3.rs
> +                export_prefix: format!("notify/{}", data_kind.as_str()),
Yeah it does append automatically. The data_kind resolves to `requests`

2024-04-12 11:57 UTC, chris13524 commented on rustfmt.toml
> +## We only use settings available in the stable channel
We can override it on a per-repo basis? I think generally good to stick to `stable` though unless there's a good reason to use `nightly`. But we can to do here if you feel strongly about it.

Is there a particular feature you are concerned about we would need `nightly` for? The only two things I care about are the sorting of imports and putting them into a single `use` block. I have a [special script for this](https://github.com/WalletConnect/notify-server/blob/fb747c58e17f53426d852513b57bf13b80d5ba6d/justfile#L111) that runs client-side. But this is compatible with `stable` format checks in CI.

2024-04-12 12:00 UTC, xDarksome commented on rustfmt.toml
> +## We only use settings available in the stable channel
why not just use nightly? if you came as far as writing a separate script

2024-04-12 13:12 UTC, chris13524 commented on rustfmt.toml
> +## We only use settings available in the stable channel
Technically I suppose it could be optional. The script doesn't do this right now but it could apply CI-level stable formatting but then only do the nightly formatting if you have it installed.

2024-04-12 13:20 UTC, chris13524 commented on rustfmt.toml
> +## We only use settings available in the stable channel
Well we were using nightly formatting across the board and then Xav changed it to stable. But then the nice import formatting broke so I added that special case for import formatting locally. I suppose it's over-engineered in retrospect. I don't mind it though

I'll change it to nightly formatting across the board in this repo

2024-04-15 11:40 UTC, xDarksome approved these changes
Please don't forget to set proper versions for the ci workflow and `utils-rs`

2024-04-26 01:08 UTC, merged